# TODO add the dependencies for the environment of your tool
name: template
channels:
  - pytorch
  - dglteam
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - flask=1.1.2
  - gunicorn=20.0.4
  - numpy=1.19
  - numpy-base=1.19
  - oauthlib=3.0
  - pillow=7.2
  - pip=20.2.2
  - python=3.7
  - python-dateutil=2.8
  - python_abi=3.7
  - pytorch=1.4
  - requests=2.24
  - requests-oauthlib=1.3
  - scikit-learn=0.23
  - scipy=1.5
  - pip:
    - multiset==2.1.1
    - pytest